name = "eigo-kiribi"
main = "./tasks/src/index.ts"
compatibility_date = "2024-04-03"

node_compat = true

[triggers]
crons = ["0 */2 * * *"]

[[kv_namespaces]]
binding = "CACHE"
id = "54f8390b169d4c198f8f42ad93bac347"
preview_id = "54f8390b169d4c198f8f42ad93bac347" # ※ TTSで無駄な費用が発生しないようにpreviewとprodで同じKVを使う

[[d1_databases]]
binding = "DB"
database_name = "eigo-d1"
database_id = "7c0ddc05-f95e-4f80-8aeb-aa569d74a3ee"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "eigo"

# Kiribi start
[[d1_databases]]
binding = "KIRIBI_DB"
database_name = "eigo-kiribi-db"
database_id = "168851f6-7469-4b32-8620-cb33d91c2e98"
migrations_dir = "./node_modules/kiribi/migrations"

[[queues.producers]]
binding = "KIRIBI_QUEUE"
queue = "eigo-kiribi-queue"

[[queues.consumers]]
queue = "eigo-kiribi-queue"
max_retries = 5

[[services]]
binding = "KIRIBI"
service = "eigo-kiribi"

[site]
bucket = "./node_modules/kiribi/client"
# Kiribi end

[[services]]
binding = "ABSORBER"
service = "eigo-kiribi"
entrypoint = "Absorber"

[[services]]
binding = "RSS_READER"
service = "eigo-kiribi"
entrypoint = "RssReader"

[[services]]
binding = "SCRAPER"
service = "eigo-kiribi"
entrypoint = "Scraper"

[[services]]
binding = "LOGO_CREATOR"
service = "eigo-kiribi"
entrypoint = "LogoCreator"

[[services]]
binding = "CALIBRATOR"
service = "eigo-kiribi"
entrypoint = "Calibrator"

