name = "eigo-absorb"
main = "src/absorb.ts"
compatibility_date = "2024-02-23"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["0 * * * *"] # Every hour

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "eigo-d1"
database_id = "7c0ddc05-f95e-4f80-8aeb-aa569d74a3ee"

[ai]
binding = "AI"
