name = "eigo"
compatibility_date = "2024-04-03"
pages_build_output_dir="dist"

[[d1_databases]]
binding = "DB"
database_name = "eigo-d1"
database_id = "7c0ddc05-f95e-4f80-8aeb-aa569d74a3ee"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "eigo"

[[services]]
binding = "Playlist"
service = "eigo-kiribi"
entrypoint = "PlaylistMaker"

[[services]]
binding = "Calibrate"
service = "eigo-kiribi"
entrypoint = "Calibrator"

[[services]]
binding = "PhrasesExtractor"
service = "eigo-kiribi"
entrypoint = "PhrasesExtractor"
